redirects:
  operations/deployment/infrastructure-setup/three-node-automation: operations/deployment/infrastructure-setup/production-automation/README.md
  operations/deployment/infrastructure-setup/three-node-automation/aws-provisioning: operations/deployment/infrastructure-setup/production-automation/aws-provisioning.md
