name: DrawIO to PNG Conversion

on: 
  push:
  pull_request:
    types:
      - closed

permissions: 
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  drawio-png-conversion:
    runs-on: ubuntu-20.04
    defaults: 
      run: 
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name:  changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check for drawio files
        run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo ${changed_file}
            export DRAWIO=0
            if [[ "${changed_file##*.}" == "drawio" ]]; then
                export DRAWIO=1
                break
            fi
          done
          if [[ "$DRAWIO" == "0" ]]; then
            echo "No drawio file. Exiting"
            exit 1 
          fi

      - name: Install snapd
        run: sudo apt install snapd -y

      - name: Install xvfb
        run: sudo apt -y install curl xvfb nano libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libappindicator3-1 libsecret-1-0 libgbm1

      - name: Install Drawio
        run: sudo snap install drawio 

      - name: Convert 
        run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            if [[ "${changed_file##*.}" == "drawio" ]]; then
              xvfb-run -a drawio -x -f png ${changed_file} --headless --disable-gpu --no-sandbox \;
            fi
          done

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Converted drawio image to png"
          git push
